# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b41fccc73778f1a29552d8ac76bab9fa0fef242d9642062cda29021e1ebc8a46eb95b63b97278393953ce8481d57a56214e58ac15d3edd99a0e4616e24e8224

test:
  secret_key_base: 57ce668378e45d6994435c2f43dc1c8aa17b22fd8db6b719eebb7941779f184eb07d20d6d78af2c33d7db8d36b4d77aff06dc06114bebfa88b0b1526ef45e20c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
